### ISSUE TITLE
check journal expansion - https://sandbox.zenodo.org/records/28835 has the abbreviated name Bull. Inst. Sci. Ind., Melb.,

### ISSUE THREAD

**Issue by jhpoelen** [TaxoDros/TaxoDros.github.io#11]
example provided by @myrmoteras -

> https://sandbox.zenodo.org/records/28835 has the abbreviated name Bull. Inst. Sci. Ind., Melb.,

expected to have the abbreviated name expanded.

**Comment by jhpoelen** [comment]
Previously, a citation string like

```.Z Bull. Inst. Sci. Ind., Melb., 29:1-..```

extracted the journal title as `Bull. Inst. Sci. Ind.` , the first text before the first comma.

Now, the text until the *last* comma is interpreted as the journal title.

Please do note that due to semi-structured nature of the journal text in the `.Z` tag, inconsistencies are likely. So, instead of adding complexities in the parsing of the journal string, I'd favor making the source data consistent . See e.g., #12  .

**Comment by myrmoteras** [comment]
ok - can we create a report and send to Bächli to correct it and get it back from him? How do you want to proceeed?

**Comment by jhpoelen** [comment]
@myrmoteras I've recorded data issues as github issues with the "data curation" tag on the https://github.com/TaxoDros/TaxoDros.github.io/issues tracker. These issues can be shared with Bächli after I finish up addressing this review round.

**Comment by jhpoelen** [comment]
Journal expansion related to Alexander, 1925 is now happening as expected in:

https://sandbox.zenodo.org/records/31731

(see attached screenshot)

![image](https://github.com/TaxoDros/TaxoDros.github.io/assets/1084872/5c13e108-50bb-4720-81a0-c633aca14b77)


related metadata:

```
{
  "metadata": {
    "http://www.w3.org/1999/02/22-rdf-syntax-ns#type": "taxodros-dros5",
    "referenceId": "alexander, 1925",
    "related_identifiers": [
      {
        "relation": "isAlternateIdentifier",
        "identifier": "urn:lsid:taxodros.uzh.ch:id:alexander%2C%201925"
      },
      {
        "relation": "isDerivedFrom",
        "identifier": "https://linker.bio/line:hash://md5/ff86b940567d278e50fa00672cf96629!/L1356-L1364"
      },
      {
        "relation": "isDerivedFrom",
        "identifier": "10.5281/zenodo.10593902"
      },
      {
        "relation": "isPartOf",
        "identifier": "https://www.taxodros.uzh.ch"
      },
      {
        "relation": "isAlternateIdentifier",
        "identifier": "hash://md5/c9d89f1ebc73de8e6e4ffbfb33b8df1f"
      }
    ],
    "creators": [
      {
        "name": "Alexander, W.B."
      }
    ],
    "publication_date": "1925",
    "title": "Natural Enemies of Prickly Pear and their Introduction into Australia.",
    "publication_type": "article",
    "journal_title": "Bulletin of the Institute of Science and Industry",
    "journal_volume": "29",
    "journal_pages": "1-",
    "taxodros:method": "ocr / part",
    "http://www.w3.org/ns/prov#wasDerivedFrom": "line:hash://md5/ff86b940567d278e50fa00672cf96629!/L1356-L1364",
    "references": [
      "Bächli, G. (2024). TaxoDros - The Database on Taxonomy of Drosophilidae hash://md5/4fa9eeed1c8cff2490483a48c718df02 hash://sha256/e05466f33c755f11bd1c2fa30eef2388bf24ff7989931bae1426daff0200af19 [Data set]. Zenodo. https://doi.org/10.5281/zenodo.10593902"
    ],
    "filename": "Alexander, 1925.pdf",
    "upload_type": "publication",
    "communities": [
      {
        "identifier": "taxodros"
      },
      {
        "identifier": "biosyslit"
      }
    ],
    "description": "Uploaded by Plazi for TaxoDros. We do not have abstracts."
  }
}
```
