### ISSUE TITLE
metadata of taxodros deposity in Zenodo

### ISSUE THREAD

**Issue by myrmoteras** [TaxoDros/TaxoDros.github.io#5]
question from [here](https://github.com/bio-guoda/preston/issues/275#issuecomment-1942890475)

# checked deposits

https://sandbox.zenodo.org/records/28809  
https://sandbox.zenodo.org/records/28811  
https://sandbox.zenodo.org/records/28813  
https://sandbox.zenodo.org/records/28815  
https://sandbox.zenodo.org/records/28817  
https://sandbox.zenodo.org/records/28819  
https://sandbox.zenodo.org/records/28821  
https://sandbox.zenodo.org/records/28823  
https://sandbox.zenodo.org/records/28825  
https://sandbox.zenodo.org/records/28827  
https://sandbox.zenodo.org/records/28829  
https://sandbox.zenodo.org/records/28831  
https://sandbox.zenodo.org/records/28833  
https://sandbox.zenodo.org/records/28835  
https://sandbox.zenodo.org/records/28837  
https://sandbox.zenodo.org/records/28839  
https://sandbox.zenodo.org/records/28841  
https://sandbox.zenodo.org/records/28843  
https://sandbox.zenodo.org/records/28845  
https://sandbox.zenodo.org/records/28847  
https://sandbox.zenodo.org/records/28849  
https://sandbox.zenodo.org/records/28851  
https://sandbox.zenodo.org/records/28853  
https://sandbox.zenodo.org/records/28855  
https://sandbox.zenodo.org/records/28857  
https://sandbox.zenodo.org/records/28859  

# Comments
## Deposits
1. Add communities: taxodros, [biosyslit](https://zenodo.org/communities/biosyslit) (BLR) 
2. Add keywords: Add a minimal set of keywords, such as "biodiversity", Drosophilidae (or if it is a different family the respective family), higher taxonomy, ie animalia, arthropoda, insecta, diptera
3. make sure, it is co-owned by biosyslit and taxodros (important for later processing)
4. is this an error (no title) or omission? https://sandbox.zenodo.org/records/28825 could be Doings of Societies: Entomological Section. The Academy of Natural Sciences of Philadelphia
5. 

## General
1. Deposits that are already in BLR from Plazi and including links to treatments etc,. should not be replaced, but the deposit number should be used in the taxodros file. If we do not do this, then we loose all the links etc. here is the list in [html](https://tb.plazi.org/GgServer/srsStats/stats?outputFields=doc.articleUuid+pubLnk.articleDoi+pubLnk.articleZenodoDepId+tax.familyEpithet+sect.tokenCount&groupingFields=doc.articleUuid+pubLnk.articleDoi+pubLnk.articleZenodoDepId+tax.familyEpithet&FP-tax.familyEpithet=Drosophilidae&FP-sect.tokenCount=22-&format=HTML), [csv](https://tb.plazi.org/GgServer/srsStats/stats?outputFields=doc.articleUuid+pubLnk.articleDoi+pubLnk.articleZenodoDepId+tax.familyEpithet+sect.tokenCount&groupingFields=doc.articleUuid+pubLnk.articleDoi+pubLnk.articleZenodoDepId+tax.familyEpithet&FP-tax.familyEpithet=Drosophilidae&FP-sect.tokenCount=22-&format=CSV&separator=%2C)  and [json](https://tb.plazi.org/GgServer/srsStats/stats?outputFields=doc.articleUuid+pubLnk.articleDoi+pubLnk.articleZenodoDepId+tax.familyEpithet+sect.tokenCount&groupingFields=doc.articleUuid+pubLnk.articleDoi+pubLnk.articleZenodoDepId+tax.familyEpithet&FP-tax.familyEpithet=Drosophilidae&FP-sect.tokenCount=22-&format=JSON)
2. add to "description" "uploaded by Plazi for Taxodros" [We do not have abstracts.
3. book chapter should be "book chapter" not "books" https://sandbox.zenodo.org/records/28855 , https://sandbox.zenodo.org/records/28843 
4. What do we do with incomplete articles, eg in this https://sandbox.zenodo.org/records/28853 pages 458 - 481 are missing, or where Bächli used just a few pages https://sandbox.zenodo.org/records/28811
6. What shall we do if we discover page range errors? leave, fix, tell Bächli? eg https://sandbox.zenodo.org/records/28839 should be 73-104 instead of 105
7. are you sure that you add the DOI to the existing DOI if there is one? E.g. https://sandbox.zenodo.org/records/28821 has a doi https://doi.org/10.1155/1915/52945 or https://sandbox.zenodo.org/records/28819 has  https://doi.org/10.5962/bhl.title.1681
8. Are you sure, you do not upload articles that are already in Zenodo? https://sandbox.zenodo.org/records/28829  has https://zenodo.org/records/225270
9. did you extend all the abbreviated journal names? https://sandbox.zenodo.org/records/28835 has the abbreviated name Bull. Inst. Sci. Ind., Melb.,
10. 

# Questions
1. Existing deposits: change the deposits and create a new version, leave as is or just updated metadata, add taxodros community?

**Comment by jhpoelen** [comment]
@myrmoteras thanks for sharing! Hoping to review your notes in the next couple of days. Thanks for being patient. . .

**Comment by jhpoelen** [comment]
> Add communities: taxodros, biosyslit (BLR)

Deposits are already registered with taxodros and biosyslit via the Zenodo metadata. Please provide examples if you have evidence to suggest otherwise.

> Add keywords: Add a minimal set of keywords, such as "biodiversity", Drosophilidae (or if it is a different family the respective family), higher taxonomy, ie animalia, arthropoda, insecta, diptera

I can add default keywords - please provide a detailed description and how you'd like to see them linked. E.g., would you want to see Animalia as a DwC kingdom terms annotation or simply a keyword text snippet. 


> make sure, it is co-owned by biosyslit and taxodros (important for later processing)

Deposits are already registered (and co-owned) with taxodros and biosyslit via the Zenodo metadata. Please provide examples if you have evidence to suggest otherwise.


> is this an error (no title) or omission? https://sandbox.zenodo.org/records/28825 could be Doings of Societies: Entomological Section. The Academy of Natural Sciences of Philadelphia

see https://github.com/TaxoDros/TaxoDros.github.io/issues/6

**Comment by jhpoelen** [comment]
> Deposits that are already in BLR from Plazi and including links to treatments etc,. should not be replaced, but the deposit number should be used in the taxodros file. If we do not do this, then we loose all the links etc. here is the list in [html](https://tb.plazi.org/GgServer/srsStats/stats?outputFields=doc.articleUuid+pubLnk.articleDoi+pubLnk.articleZenodoDepId+tax.familyEpithet+sect.tokenCount&groupingFields=doc.articleUuid+pubLnk.articleDoi+pubLnk.articleZenodoDepId+tax.familyEpithet&FP-tax.familyEpithet=Drosophilidae&FP-sect.tokenCount=22-&format=HTML), [csv](https://tb.plazi.org/GgServer/srsStats/stats?outputFields=doc.articleUuid+pubLnk.articleDoi+pubLnk.articleZenodoDepId+tax.familyEpithet+sect.tokenCount&groupingFields=doc.articleUuid+pubLnk.articleDoi+pubLnk.articleZenodoDepId+tax.familyEpithet&FP-tax.familyEpithet=Drosophilidae&FP-sect.tokenCount=22-&format=CSV&separator=%2C) and [json](https://tb.plazi.org/GgServer/srsStats/stats?outputFields=doc.articleUuid+pubLnk.articleDoi+pubLnk.articleZenodoDepId+tax.familyEpithet+sect.tokenCount&groupingFields=doc.articleUuid+pubLnk.articleDoi+pubLnk.articleZenodoDepId+tax.familyEpithet&FP-tax.familyEpithet=Drosophilidae&FP-sect.tokenCount=22-&format=JSON)

The scope of the project is TaxoDros. As discussed, any other alignment beyond the 183 existing TaxaDros records would be done as part of future projects.

**Comment by jhpoelen** [comment]
> add to "description" "uploaded by Plazi for Taxodros" [We do not have abstracts.

see https://github.com/TaxoDros/TaxoDros.github.io/issues/7 .

**Comment by jhpoelen** [comment]
> book chapter should be "book chapter" not "books" https://sandbox.zenodo.org/records/28855 , https://sandbox.zenodo.org/records/28843

see https://github.com/TaxoDros/TaxoDros.github.io/issues/8 .

**Comment by jhpoelen** [comment]
> What do we do with incomplete articles, eg in this https://sandbox.zenodo.org/records/28853 pages 458 - 481 are missing, or where Bächli used just a few pages https://sandbox.zenodo.org/records/28811

> What shall we do if we discover page range errors? leave, fix, tell Bächli? eg https://sandbox.zenodo.org/records/28839 should be 73-104 instead of 105

I favor to fix data issues at the source, especially for actively managed and curated projects. Suggest to create separate issues and share them with Bächli directly.

**Comment by jhpoelen** [comment]
> are you sure that you add the DOI to the existing DOI if there is one? E.g. https://sandbox.zenodo.org/records/28821 has a doi https://doi.org/10.1155/1915/52945 or https://sandbox.zenodo.org/records/28819 has https://doi.org/10.5962/bhl.title.1681

see https://github.com/TaxoDros/TaxoDros.github.io/issues/9

**Comment by jhpoelen** [comment]
> did you extend all the abbreviated journal names? https://sandbox.zenodo.org/records/28835 has the abbreviated name Bull. Inst. Sci. Ind., Melb.,

Yes, all journal names are extended as far as the extensions are available through TaxoDros expansion table. I made a note of the specific example you gave at https://github.com/TaxoDros/TaxoDros.github.io/issues/11 .

**Comment by jhpoelen** [comment]
> Existing deposits: change the deposits and create a new version, leave as is or just updated metadata, add taxodros community?

Would you happen to have some personnel to edit metadata records of the existing 180 (or so) TaxoDros associated record and add TaxoDros identifiers? This would make the update process easier to automated and would save me hours of copy-paste work.

**Comment by myrmoteras** [comment]
> > Existing deposits: change the deposits and create a new version, leave as is or just updated metadata, add taxodros community?
> 
> Would you happen to have some personnel to edit metadata records of the existing 180 (or so) TaxoDros associated record and add TaxoDros identifiers? This would make the update process easier to automated and would save me hours of copy-paste work.

Do you mean all the articles that are in Zenodo AND are in Taxodros? Not just the ones that we uploaded before, but all the ones that we processed independently of Taxodros?

**Comment by jhpoelen** [comment]
> Do you mean all the articles that are in Zenodo AND are in Taxodros? Not just the ones that we uploaded before, but all the ones that we processed independently of Taxodros?

As far as I am concerned, the scope of the project is TaxoDros and only TaxoDros.

**Comment by myrmoteras** [comment]
> > Existing deposits: change the deposits and create a new version, leave as is or just updated metadata, add taxodros community?
> 
> Would you happen to have some personnel to edit metadata records of the existing 180 (or so) TaxoDros associated record and add TaxoDros identifiers? This would make the update process easier to automated and would save me hours of copy-paste work.

Can you define what exactly this person has to add? That means all the publications that are already in Zenodo/BLR and are in the taxodros stack?!

**Comment by jhpoelen** [comment]
> Can you define what exactly this person has to add? That means all the publications that are already in Zenodo/BLR and are in the taxodros stack?!

Thanks for asking. Each of the existing 180 or so TaxoDros records needs a TaxoDros lsid to tie the original TaxoDros record to their derived Zenodo record.

For instance, TaxoDros record associated with https://linker.bio/line:hash://md5/e83039fdbc676f9c9e915e08b0c8c2f1!/L1284-L1291

```
.TEXT;
aldrich, 1922
.A Aldrich, J.M.,
.J 1922
.S (no title).
.Z Ent. News, 33:317-318.
.K ocr / p 811824
.P Aldrich, 1922.pdf
```

is associated with id ```aldrich, 1922``` encoded as lsid:

urn:lsid:taxodros.uzh.ch:id:aldrich,%201922

And this id ties the TaxoDros record with their derived Zenodo record. With this, you can do targeted, automated, updates. 

![image](https://github.com/TaxoDros/TaxoDros.github.io/assets/1084872/6e98d91a-1fbe-4767-afe8-b0948a33f4cf)

**Comment by jhpoelen** [comment]
@myrmoteras please feel free to re-open this old review ticket if needed.
